spring:
  application:
    name: proofly-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:25MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:25MB}

server:
  port: ${SERVER_PORT:8080}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

proofly:
  auth:
    # 用户密码BCrypt加密的盐
    jwt-secret: ${PROOFLY_AUTH_JWT_SECRET:proofly-local-dev-jwt-secret-must-be-at-least-32-bytes}
    access-token-ttl-minutes: ${PROOFLY_AUTH_ACCESS_TOKEN_TTL_MINUTES:120}
    refresh-token-ttl-days: ${PROOFLY_AUTH_REFRESH_TOKEN_TTL_DAYS:7}
    redis-prefix: ${PROOFLY_AUTH_REDIS_PREFIX:proofly}
    rsa:
      public-key: ${PROOFLY_AUTH_RSA_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsV41XoYss/jAIFCzbpscdhOarsQ8DlKkbEdxA79ADBCM1U2B3nHJYU+Fh2INlvlh6sBWI5Lr5mu8tLpSbiVLbiJyCuN2A8Lh2U7WDBojcab67qmxntUyEWPVb2n/gZVjGT4neAxnUT0dFnN5sDFv3/9gZT9c/vdUIbmoWZQrrYX1bYXW694YBYiNxzKCStM/gH0Ew7RuoWSBcAB7BfVEmvE9v/qYD8/YytqaGztRK5UDuiOY555qqQYzrMHVQza5ihCR0zyck3J4w8wb3b03gRZIw2i7uWmEpxTQgGbRuypJv3ip9klVTyJCeSsqOwbG98Ru/2whJJjt3XICEcGxjQIDAQAB}
      private-key: ${PROOFLY_AUTH_RSA_PRIVATE_KEY:MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxXjVehiyz+MAgULNumxx2E5quxDwOUqRsR3EDv0AMEIzVTYHecclhT4WHYg2W+WHqwFYjkuvma7y0ulJuJUtuInIK43YDwuHZTtYMGiNxpvruqbGe1TIRY9Vvaf+BlWMZPid4DGdRPR0Wc3mwMW/f/2BlP1z+91QhuahZlCuthfVthdbr3hgFiI3HMoJK0z+AfQTDtG6hZIFwAHsF9USa8T2/+pgPz9jK2pobO1ErlQO6I5jnnmqpBjOswdVDNrmKEJHTPJyTcnjDzBvdvTeBFkjDaLu5aYSnFNCAZtG7Kkm/eKn2SVVPIkJ5Kyo7Bsb3xG7/bCEkmO3dcgIRwbGNAgMBAAECggEAKHEt85fd9QpcynGEPE3PW0gEjuFtPSnQVmUiyoMu6CFU72T9Hfqte4v9ix1LMne6ASQqb/GV6uP5cu8CER3dWWcuwDdVpy1mQF22tis2ljlIAae9OZVslWUBW2ZcrVAh+LVAnCGd5DruWTpqzoczNmy9LtDYFEXST99MmOJNZELkMrSp7doi9Y50nJZaw+W5W69ljxnJLNXlsN+lFoK44Jn9GFLnTEgiJ0tbCYnIu3OTlJNXpbQx549X66V2QpVACYwHNZWk9AR11kjgB1fULOjY556c/wJew22TonhMEVtx9KUJFIamZ7bc1TUS7zahuBLh+6sRCzJH7990lG8GOQKBgQDc47NTVC9KnNhsLJVUhoJdGr1tkJqR9TsrA1PLdB9sExHdDkGB6iH+HWG+wEHxSWAckknYQJ4LAJQbtWuMUx+/LLEwsDvMfC3UDIwdInqAWh9rSyvQMCvj5RgBJVszAKIYJMAAcHBWqB+BOGEy34YGvfZ751OGcW/5EALSlf6CNQKBgQDNj484IeGgS04A6GVQx3+RS1cTam4HTVd+Xtf8fdvnWj2qf/byOlURL9wRcg/VZJoW6U4M0XBX2akBL40+iuTYTWEUYsGWpopKJ5TtdHaCA8walSAomntIpTwuuubHNBIyAWP0vekmoYqOKnJhDcJXBJIp/beRZbCtmfXZKgJc+QKBgQDOSeTOnJ9x6hsAo35uqxQSiYeBTHvedgzk9b2LE47I6uJS9R5eit9mJ+CCOaEcCy+0XzaRvH8cvVSUsBCZw4OxkbaFRwEBzrMqBvHPv8RyHDidhl2Ll4FV2z1YzJ9oeV3oeGHLxzZS575Meu/jh/buUvhf7MEHnOc6ziYkryo6RQKBgB1G0wkVmkLwNr3eW3+zyjFxX4d+YwlbNJjk/TIS4t0Cd0HvU8aQFEmMXXWGn0avO1sEA3/D3JJGh9GJaj58HbfI3Yi/v/6q3YtOM+HV8oL1833du2TNC73++qFVMUUx312L4SacXbaIz2kMFppIEWO/XOnqHtjweMdg5Cj32LpRAoGAa6mWNEfVubFodWdx1C61iN4xh2+97iJ8dzOhflx2UnFqunOrVhlCoLL8+fni7jRkaW5f3wnBCDk8xPJqXmFnNS7PgFjHeMQVyI/3VjhdMQf8DwAKSFGQd5xwICAxhI/LUPqAWefWw7Emp6NatlRNdpXSXpnfRchh8+M8MUlekNg=}
