-- Proofly MySQL schema
-- Target: MySQL 8.0
-- Charset: utf8mb4
-- Collation: utf8mb4_0900_ai_ci
--
-- Notes:
-- 1. IDs are BIGINT global IDs generated by the application.
-- 2. This MVP schema creates tables and indexes only. Foreign keys are not
--    declared here to avoid circular initialization constraints between
--    project, project_version, and file_object.
-- 3. Confirmation records, audit logs, and access logs are append-oriented
--    business evidence and should not be physically deleted.

CREATE DATABASE IF NOT EXISTS `proofly`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE `proofly`;

CREATE TABLE IF NOT EXISTS `store` (
  `id` BIGINT NOT NULL COMMENT '门店 ID',
  `name` VARCHAR(100) NOT NULL COMMENT '门店名称',
  `contact_name` VARCHAR(50) NULL COMMENT '联系人',
  `contact_phone` VARCHAR(20) NULL COMMENT '联系电话',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '门店状态：active, disabled',
  `plan_type` VARCHAR(32) NOT NULL DEFAULT 'free' COMMENT '套餐类型：free, pro',

  `plan_expires_at` DATETIME(3) NULL COMMENT '套餐过期时间',
  `invite_code` VARCHAR(32) NULL COMMENT '门店专属邀请码',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_store_invite_code` (`invite_code`),
  KEY `idx_store_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='门店信息表';

CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT NOT NULL COMMENT '用户 ID',
  `store_id` BIGINT NOT NULL COMMENT '所属门店',
  `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  `nickname` VARCHAR(64) NOT NULL COMMENT '昵称',
  `phone` VARCHAR(30) NULL COMMENT '手机号',
  `email` VARCHAR(128) NULL COMMENT '邮箱',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '用户状态：active, disabled, locked',
  `last_login_at` DATETIME(3) NULL COMMENT '最后登录时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_store_username` (`store_id`, `username`, `deleted`),
  UNIQUE KEY `uk_user_store_phone` (`store_id`, `phone`, `deleted`),
  KEY `idx_user_store_status` (`store_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='后台用户表';

CREATE TABLE IF NOT EXISTS `role` (
  `id` BIGINT NOT NULL COMMENT '角色 ID',
  `store_id` BIGINT NULL COMMENT '门店 ID，系统内置角色可为空',
  `code` VARCHAR(32) NOT NULL COMMENT '角色编码：owner, designer, admin',
  `name` VARCHAR(64) NOT NULL COMMENT '角色名称',
  `description` VARCHAR(255) NULL COMMENT '角色说明',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_store_code` (`store_id`, `code`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='角色定义表';

CREATE TABLE IF NOT EXISTS `user_role` (
  `id` BIGINT NOT NULL COMMENT '关系 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `user_id` BIGINT NOT NULL COMMENT '用户 ID',
  `role_id` BIGINT NOT NULL COMMENT '角色 ID',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`user_id`, `role_id`),
  KEY `idx_user_role_store_user` (`store_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户角色关系表';

CREATE TABLE IF NOT EXISTS `project` (
  `id` BIGINT NOT NULL COMMENT '项目 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `name` VARCHAR(150) NOT NULL COMMENT '项目名称',
  `customer_name` VARCHAR(80) NULL COMMENT '客户名称',
  `customer_contact` VARCHAR(120) NULL COMMENT '客户联系方式',
  `owner_user_id` BIGINT NOT NULL COMMENT '项目负责人',
  `status` VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '项目状态',
  `current_version_id` BIGINT NULL COMMENT '当前展示版本',
  `confirmed_version_id` BIGINT NULL COMMENT '最终确认版本',
  `remark` VARCHAR(1000) NULL COMMENT '项目备注',
  `archived_at` DATETIME(3) NULL COMMENT '归档时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_project_store_status` (`store_id`, `status`, `deleted`),
  KEY `idx_project_store_owner` (`store_id`, `owner_user_id`, `deleted`),
  KEY `idx_project_customer` (`store_id`, `customer_name`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='审稿项目主表';

CREATE TABLE IF NOT EXISTS `project_status_log` (
  `id` BIGINT NOT NULL COMMENT '日志 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `from_status` VARCHAR(32) NULL COMMENT '变更前状态',
  `to_status` VARCHAR(32) NOT NULL COMMENT '变更后状态',
  `action` VARCHAR(64) NOT NULL COMMENT '触发动作',
  `operator_type` VARCHAR(32) NOT NULL COMMENT '操作人类型：user, customer, system',
  `operator_id` BIGINT NULL COMMENT '后台用户 ID',
  `operator_name` VARCHAR(80) NULL COMMENT '操作人名称',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_project_status_log_project` (`store_id`, `project_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='项目状态流转日志';

CREATE TABLE IF NOT EXISTS `project_version` (
  `id` BIGINT NOT NULL COMMENT '版本 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `version_no` INT NOT NULL COMMENT '项目内递增版本号',
  `version_name` VARCHAR(32) NOT NULL COMMENT '展示名称，如 V1',
  `file_id` BIGINT NOT NULL COMMENT '主文件 ID',
  `uploaded_by` BIGINT NULL COMMENT '上传人',
  `description` VARCHAR(1000) NULL COMMENT '版本说明',
  `is_current` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否当前版本',
  `is_confirmed` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已确认',
  `confirmed_at` DATETIME(3) NULL COMMENT '确认时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_project_version_no` (`project_id`, `version_no`),
  KEY `idx_project_version_project` (`store_id`, `project_id`, `created_at`),
  KEY `idx_project_version_current` (`project_id`, `is_current`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='设计稿版本表';

CREATE TABLE IF NOT EXISTS `file_object` (
  `id` BIGINT NOT NULL COMMENT '文件 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `project_id` BIGINT NULL COMMENT '项目 ID',
  `version_id` BIGINT NULL COMMENT '版本 ID',
  `object_key` VARCHAR(512) NOT NULL COMMENT 'MinIO 对象 key',
  `bucket` VARCHAR(100) NOT NULL COMMENT 'MinIO bucket',
  `original_filename` VARCHAR(255) NOT NULL COMMENT '原始文件名',
  `safe_filename` VARCHAR(255) NOT NULL COMMENT '安全文件名',
  `file_ext` VARCHAR(20) NULL COMMENT '文件扩展名',
  `mime_type` VARCHAR(100) NULL COMMENT 'MIME 类型',
  `file_size` BIGINT NOT NULL COMMENT '文件大小，单位字节',
  `sha256` CHAR(64) NULL COMMENT '文件 SHA-256',
  `file_role` VARCHAR(32) NOT NULL COMMENT '文件角色：original, preview, attachment, confirmation, temp',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '上传人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_file_object_key` (`bucket`, `object_key`),
  KEY `idx_file_project_version` (`store_id`, `project_id`, `version_id`),
  KEY `idx_file_sha256` (`sha256`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='文件元数据表';

CREATE TABLE IF NOT EXISTS `review_link` (
  `id` BIGINT NOT NULL COMMENT '链接 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `current_version_id` BIGINT NULL COMMENT '链接当前指向版本',
  `token_hash` CHAR(64) NOT NULL COMMENT '访问 token 哈希',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '链接状态：active, disabled, expired',
  `expires_at` DATETIME(3) NULL COMMENT '过期时间',
  `max_access_count` INT NULL COMMENT '最大访问次数',
  `access_count` INT NOT NULL DEFAULT 0 COMMENT '已访问次数',
  `last_access_at` DATETIME(3) NULL COMMENT '最近访问时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_link_token_hash` (`token_hash`),
  KEY `idx_review_link_project` (`store_id`, `project_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户审稿链接表';

CREATE TABLE IF NOT EXISTS `review_access_log` (
  `id` BIGINT NOT NULL COMMENT '日志 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `review_link_id` BIGINT NOT NULL COMMENT '审稿链接 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `version_id` BIGINT NULL COMMENT '访问时版本 ID',
  `ip` VARCHAR(64) NULL COMMENT '访问 IP',
  `user_agent` VARCHAR(512) NULL COMMENT 'User-Agent',
  `referer` VARCHAR(512) NULL COMMENT '来源页面',
  `accessed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '访问时间',
  PRIMARY KEY (`id`),
  KEY `idx_review_access_project` (`store_id`, `project_id`, `accessed_at`),
  KEY `idx_review_access_link` (`review_link_id`, `accessed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户访问日志表';

CREATE TABLE IF NOT EXISTS `annotation` (
  `id` BIGINT NOT NULL COMMENT '标注 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `version_id` BIGINT NOT NULL COMMENT '版本 ID',
  `review_link_id` BIGINT NULL COMMENT '来源审稿链接',
  `type` VARCHAR(32) NOT NULL COMMENT '标注类型：point, rect, text',
  `x_ratio` DECIMAL(10,6) NULL COMMENT 'X 相对坐标',
  `y_ratio` DECIMAL(10,6) NULL COMMENT 'Y 相对坐标',
  `width_ratio` DECIMAL(10,6) NULL COMMENT '宽度相对比例',
  `height_ratio` DECIMAL(10,6) NULL COMMENT '高度相对比例',
  `content` VARCHAR(2000) NOT NULL COMMENT '修改意见',
  `media_url` VARCHAR(500) NULL COMMENT '语音/媒体文件URL',
  `media_duration` INT NULL COMMENT '媒体文件时长(秒)',
  `customer_name` VARCHAR(80) NULL COMMENT '客户名称',
  `customer_contact` VARCHAR(120) NULL COMMENT '客户联系方式',
  `status` VARCHAR(32) NOT NULL DEFAULT 'open' COMMENT '标注状态：open, resolved, ignored',
  `resolved_by` BIGINT NULL COMMENT '处理人',
  `resolved_at` DATETIME(3) NULL COMMENT '处理时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人，客户提交可为空',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_annotation_version` (`store_id`, `project_id`, `version_id`, `status`),
  KEY `idx_annotation_project` (`store_id`, `project_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='标注意见表';

CREATE TABLE IF NOT EXISTS `annotation_comment` (
  `id` BIGINT NOT NULL COMMENT '回复 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `annotation_id` BIGINT NOT NULL COMMENT '标注 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `version_id` BIGINT NOT NULL COMMENT '版本 ID',
  `reply_type` VARCHAR(32) NOT NULL COMMENT '回复人类型：user, customer, system',
  `reply_user_id` BIGINT NULL COMMENT '后台用户 ID',
  `reply_name` VARCHAR(80) NULL COMMENT '回复人名称',
  `content` VARCHAR(2000) NOT NULL COMMENT '回复内容',
  `media_url` VARCHAR(500) NULL COMMENT '语音/媒体文件URL',
  `media_duration` INT NULL COMMENT '媒体文件时长(秒)',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_annotation_comment` (`annotation_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='标注回复表';

CREATE TABLE IF NOT EXISTS `referral_record` (
  `id` BIGINT NOT NULL COMMENT '记录 ID',
  `inviter_store_id` BIGINT NOT NULL COMMENT '邀请人门店 ID',
  `inviter_user_id` BIGINT NOT NULL COMMENT '邀请人用户 ID',
  `invitee_store_id` BIGINT NOT NULL COMMENT '受邀人门店 ID',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '状态：pending, rewarded',
  `rewarded_at` DATETIME(3) NULL COMMENT '发奖时间',
  `trigger_project_id` BIGINT NULL COMMENT '触发发奖的项目 ID',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_referral_invitee` (`invitee_store_id`),
  KEY `idx_referral_inviter` (`inviter_store_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='推荐奖励记录表';

CREATE TABLE IF NOT EXISTS `confirmation_record` (
  `id` BIGINT NOT NULL COMMENT '确认记录 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `project_id` BIGINT NOT NULL COMMENT '项目 ID',
  `version_id` BIGINT NOT NULL COMMENT '确认版本 ID',
  `review_link_id` BIGINT NULL COMMENT '审稿链接 ID',
  `customer_name` VARCHAR(80) NULL COMMENT '确认人名称',
  `customer_contact` VARCHAR(120) NULL COMMENT '确认人联系方式',
  `confirmed_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '确认时间',
  `ip` VARCHAR(64) NULL COMMENT '确认 IP',
  `user_agent` VARCHAR(512) NULL COMMENT 'User-Agent',
  `status` VARCHAR(32) NOT NULL DEFAULT 'valid' COMMENT '确认记录状态：valid, voided',
  `voided_at` DATETIME(3) NULL COMMENT '作废时间',
  `void_reason` VARCHAR(500) NULL COMMENT '作废原因',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_confirmation_project_status` (`project_id`, `status`),
  KEY `idx_confirmation_version` (`store_id`, `project_id`, `version_id`),
  KEY `idx_confirmation_time` (`store_id`, `confirmed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户确认记录表';

CREATE TABLE IF NOT EXISTS `audit_log` (
  `id` BIGINT NOT NULL COMMENT '日志 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `action` VARCHAR(64) NOT NULL COMMENT '动作类型',
  `target_type` VARCHAR(64) NOT NULL COMMENT '业务对象类型',
  `target_id` BIGINT NULL COMMENT '业务对象 ID',
  `operator_type` VARCHAR(32) NOT NULL COMMENT '操作人类型：user, customer, system',
  `operator_id` BIGINT NULL COMMENT '后台用户 ID',
  `operator_name` VARCHAR(80) NULL COMMENT '操作人名称',
  `summary` VARCHAR(500) NOT NULL COMMENT '日志摘要',
  `extra_json` JSON NULL COMMENT '扩展信息',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_audit_target` (`store_id`, `target_type`, `target_id`, `created_at`),
  KEY `idx_audit_action` (`store_id`, `action`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='通用审计日志表';

CREATE TABLE IF NOT EXISTS `notification` (
  `id` BIGINT NOT NULL COMMENT '通知 ID',
  `store_id` BIGINT NOT NULL COMMENT '门店 ID',
  `receiver_user_id` BIGINT NOT NULL COMMENT '接收人',
  `project_id` BIGINT NULL COMMENT '关联项目',
  `type` VARCHAR(64) NOT NULL COMMENT '通知类型',
  `title` VARCHAR(150) NOT NULL COMMENT '标题',
  `content` VARCHAR(1000) NULL COMMENT '内容',
  `read_at` DATETIME(3) NULL COMMENT '已读时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_notification_receiver` (`store_id`, `receiver_user_id`, `read_at`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='站内通知表';

CREATE TABLE IF NOT EXISTS `system_config` (
  `id` BIGINT NOT NULL COMMENT '配置 ID',
  `store_id` BIGINT NULL COMMENT '门店 ID，系统默认配置可为空',
  `config_key` VARCHAR(100) NOT NULL COMMENT '配置键',
  `config_value` VARCHAR(1000) NOT NULL COMMENT '配置值',
  `value_type` VARCHAR(32) NOT NULL DEFAULT 'string' COMMENT '值类型：string, number, boolean, json',
  `description` VARCHAR(255) NULL COMMENT '配置说明',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `created_by` BIGINT NULL COMMENT '创建人',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `updated_by` BIGINT NULL COMMENT '更新人',
  `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_system_config_key` (`store_id`, `config_key`, `deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业务配置表';

-- ---------------------------------------------------------
-- 初始基础数据 (仅供开发/本地环境参考)
-- ---------------------------------------------------------

INSERT INTO `store` (
  `id`,
  `name`,
  `contact_name`,
  `contact_phone`,
  `status`,
  `created_at`,
  `updated_at`,
  `deleted`
) VALUES (
  20001,
  '默认门店',
  '管理员',
  '13800000000',
  'active',
  CURRENT_TIMESTAMP(3),
  CURRENT_TIMESTAMP(3),
  0
) ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `status` = VALUES(`status`),
  `updated_at` = CURRENT_TIMESTAMP(3),
  `deleted` = 0;

INSERT INTO `role` (
  `id`,
  `store_id`,
  `code`,
  `name`,
  `description`,
  `created_at`,
  `updated_at`,
  `deleted`
) VALUES
  (21001, 20001, 'owner', '门店老板', '管理门店项目和员工', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
  (21002, 20001, 'designer', '设计师', '创建项目、上传版本、处理标注', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0),
  (21003, 20001, 'admin', '管理员', '平台或系统管理员', CURRENT_TIMESTAMP(3), CURRENT_TIMESTAMP(3), 0)
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `description` = VALUES(`description`),
  `updated_at` = CURRENT_TIMESTAMP(3),
  `deleted` = 0;

INSERT INTO `user` (
  `id`,
  `store_id`,
  `username`,
  `nickname`,
  `phone`,
  `email`,
  `password_hash`,
  `status`,
  `created_at`,
  `updated_at`,
  `deleted`
) VALUES (
  22001,
  20001,
  'admin',
  '系统管理员',
  '13800000000',
  'admin@proofly.local',
  '$2y$10$7BwVGcyIudUBpNDL/k.wkO8n5OFl0F/X1/JxNQyXnY8.uSvpw0PaW',
  'active',
  CURRENT_TIMESTAMP(3),
  CURRENT_TIMESTAMP(3),
  0
) ON DUPLICATE KEY UPDATE
  `nickname` = VALUES(`nickname`),
  `phone` = VALUES(`phone`),
  `email` = VALUES(`email`),
  `password_hash` = VALUES(`password_hash`),
  `status` = VALUES(`status`),
  `updated_at` = CURRENT_TIMESTAMP(3),
  `deleted` = 0;

INSERT INTO `user_role` (
  `id`,
  `store_id`,
  `user_id`,
  `role_id`,
  `created_at`
) VALUES
  (23001, 20001, 22001, 21001, CURRENT_TIMESTAMP(3)),
  (23002, 20001, 22001, 21003, CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE
  `store_id` = VALUES(`store_id`);
